name: mastering github action
on: 
    push:
        branches: main
jobs:
    # job
    checkout:
        # runner
        runs-on: ubuntu-24.04
        steps:
            # step
            - name: whoami
              run: echo "i am ${{ github.repository_owner }}"

            - name: cloning repo
              run: actions/checkout@v7

            - run: ls